name: Deploy to NearlyFreeSpeech.Net

# Only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

jobs:
    deploy_job:
    runs-on: ubuntu-latest
    name: deploy

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set Up Bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest

        - name: Install dependencies and build
          run: |
            bun i
            bun run build

        - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'helenclx_leilukin'
            server: 'ssh.nyc1.nearlyfreespeech.net'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: './_site/*'
            remote_path: '/home/public'
